# Generated by Django 5.0.3 on 2024-04-27 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlackList",
            fields=[
                (
                    "stu_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("expire_time", models.DateField(blank=True, null=True)),
                (
                    "banned_reason",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("creation_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "black_list",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("space_name", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("eng_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Space",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "signature",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("start_time", models.IntegerField()),
                ("date", models.DateField()),
                ("usable", models.IntegerField()),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                ("user_phone", models.CharField(blank=True, max_length=255, null=True)),
                ("user_dormnumber", models.IntegerField(blank=True, null=True)),
                ("change_pwd", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public_borrow.space",
                    ),
                ),
            ],
            options={
                "db_table": "Register",
                "managed": True,
                "unique_together": {("space", "start_time", "date")},
            },
        ),
    ]
