# Generated by Django 5.0.4 on 2024-04-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentINFO',
            fields=[
                ('request_id', models.IntegerField(max_length=255, unique=True)),
                ('stu_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'studentINFO',
                'managed': True,
            },
        ),
    ]
