# Generated by Django 5.0.3 on 2024-04-27 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dormadmin",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="dormadmin",
            table="dormAdmin",
        ),
    ]
